name: dio_retry
description: A starting point for Dart libraries or applications.
version: 0.1.10-beta
homepage: https://github.com/aloisdeniel/dio_retry

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  logging: ^1.1.1
  dio: ^5.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
